project_name: mpt
dist: .bin
builds:
  - id: mpt
    binary: "mpt"
    main: ./cmd/mpt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags: "-s -w -X main.revision={{.Tag}}-{{.ShortCommit}}-{{.CommitDate}}"

archives:
  - id: mpt
    name_template: >-
     {{.ProjectName}}_
     {{- .Tag}}_
     {{- if eq .Os "darwin"}}macos
     {{- else if eq .Os "windows"}}win
     {{- else}}{{.Os}}{{end}}_
     {{- if eq .Arch "amd64"}}x86_64
     {{- else if eq .Arch "386"}}i386
     {{- else}}{{.Arch}}{{end}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - completions/*
    rlcp: true


brews:
  -
    name: mpt
    tap:
      owner: umputun
      name: homebrew-apps
      branch: master
    directory: Formula
    commit_author:
      name: umputun
      email: umputun@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/umputun/mpt"
    description: "MPT is a command-line utility that sends prompts to multiple AI language model providers in parallel and combines the results"
    license: "MIT"
    extra_install: |
      bash_completion.install "completions/mpt.bash" => "mpt"
      zsh_completion.install "completions/mpt.zsh" => "_mpt"
      fish_completion.install "completions/mpt.fish" => "mpt.fish"

nfpms:
  - id: mpt
    package_name: mpt
    file_name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    vendor: Umputun
    homepage: https://github.com/umputun/mpt
    maintainer: Umputun <umputun@gmail.com>
    description: MPT is a command-line utility that sends prompts to multiple AI language model providers in parallel and combines the results
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
    release: 1
    contents:
      - src: completions/mpt.bash
        dst: /usr/share/bash-completion/completions/mpt
      - src: completions/mpt.zsh
        dst: /usr/share/zsh/vendor-completions/_mpt
      - src: completions/mpt.fish
        dst: /usr/share/fish/vendor_completions.d/mpt.fish
